# -*- coding: utf-8 -*-
"""Tugas Analitik Beras 065002400015 - Charin Stefany.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_qGmN0K_fVJmr112m3XDmWQT9DMpPKh
"""

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load data
data_charin = pd.read_csv('hargaberas1.csv')

#2 Deteksi otomatis kolom pasar
harga_cols = [col for col in data_charin.columns if 'Pasar' in col]

# 3. Bersihkan nilai harga: hapus koma, ubah ke float
for col in harga_cols + ['PIBC']:
    data_charin[col] = (
        data_charin[col]
        .astype(str)
        .str.replace('.', '', regex=False)   # Hapus ribuan
        .str.replace(',', '.', regex=False)  # Ubah desimal ke format Python
        .astype(float)
    )

# 4. Hitung harga rata-rata dari seluruh pasar tradisional
data_charin['harga_pasar_tradisional'] = data_charin[harga_cols].mean(axis=1)

# 5. Siapkan data regresi: harga sebagai X, jarak sebagai y
X = data_charin[['harga_pasar_tradisional']]
X = sm.add_constant(X)  # Tambahkan intercept
y = data_charin['Jarak dari PIBC']

# 6. Bangun model regresi
model = sm.OLS(y, X).fit()
data_charin['prediksi_jarak'] = model.predict(X)

# 7. Cetak ringkasan model
print(model.summary())

# 8. Visualisasi
plt.figure(figsize=(6, 4))
sns.scatterplot(x=data_charin['harga_pasar_tradisional'], y=data_charin['Jarak dari PIBC'], s=80, label='Data Aktual')
sns.lineplot(x=data_charin['harga_pasar_tradisional'], y=data_charin['prediksi_jarak'], color='red', label='Garis Regresi')
plt.xlabel('Harga Pasar Tradisional (Rata-rata)')
plt.ylabel('Jarak dari PIBC (km)')
plt.title('Pengaruh Harga Pasar Tradisional terhadap Jarak dari PIBC')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import statsmodels.api as sm

# 1. Tambahkan intercept (konstanta)
X_sm = sm.add_constant(X)
# menambahkan kolom konstanta (bias)
y = data_charin['harga_pasar_tradisional']

# 2. Model regresi dengan statsmodels
model_sm = sm.OLS(y, X_sm).fit()